version: '3.8'

services:
  php:
    build: .
    container_name: php
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: CourseReport
      DB_USERNAME: devuser
      DB_PASSWORD: devpassword
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dev_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html

volumes:
  db_data: